from flask import Flask, jsonify, request
import os
import requests
import json

app = Flask(__name__)

# Load secrets from environment variables
API_KEY = os.environ.get("API_KEY")
DISCORD_WEBHOOK_URL = os.environ.get("WEBHOOK_URL")

@app.route('/')
def home():
    return "Web App is Running!"

@app.route('/webhook', methods=['POST'])
def webhook():
    if not DISCORD_WEBHOOK_URL:
        return jsonify({"status": "error", "message": "Missing Discord webhook URL"}), 500

    if not API_KEY:
        return jsonify({"status": "error", "message": "Missing API key"}), 500

    # Validate API key if required
    auth_key = request.headers.get('Authorization')
    if auth_key != f"Bearer {API_KEY}":
        return jsonify({"status": "error", "message": "Unauthorized"}), 403

    data = request.json
    if not data:
        return jsonify({"status": "error", "message": "No data received"}), 400

    print("Payload received from Roblox:", json.dumps(data, indent=4))  # Debug

    # Extract details
    place_id = data.get('placeId', 'N/A')
    server_id = data.get('serverId', 'N/A')
    player_data = data.get('playerData', 'No players in the server.')
    join_leave_logs = data.get('joinLeaveLogs', 'No recent activity.')
    chat_logs = data.get('chatLogs', 'No messages.')

    # Prepare Discord webhook payload
    discord_payload = {
        "embeds": [
            {
                "title": "Roblox Moderation Log",
                "description": "Server Activity Report",
                "color": 3447003,  # Blue color
                "fields": [
                    {"name": "Place ID", "value": str(place_id), "inline": True},
                    {"name": "Server ID", "value": str(server_id), "inline": True},
                    {"name": "Players", "value": player_data, "inline": False},
                    {"name": "Join/Leave Logs", "value": join_leave_logs, "inline": False},
                    {"name": "Chat Logs", "value": chat_logs, "inline": False},
                ],
                "footer": {
                    "text": "Generated by Roblox Moderation System",
                    "icon_url": "https://i.imgur.com/AfFp7pu.png",  # Optional footer icon
                },
            }
        ]
    }

    # Send data to Discord webhook
    try:
        response = requests.post(DISCORD_WEBHOOK_URL, json=discord_payload)
        if response.status_code == 204:  # No Content
            print("Message sent to Discord successfully!")
            return jsonify({"status": "success"}), 200
        else:
            print("Failed to send message to Discord:", response.status_code, response.text)
            return jsonify({"status": "error", "message": "Failed to send to Discord"}), 500
    except Exception as e:
        print("Error while sending to Discord:", str(e))
        return jsonify({"status": "error", "message": str(e)}), 500


if __name__ == "__main__":
    app.run(host="0.0.0.0", port=8080)